---
  tasks:
          - name: debug
            debug:
                    msg: "Bonjour ici l'environnement {{env}}"

          - name: "Pour créer un utilisateur"
            when : ansible_distribution == "Ubuntu"
            user:
                 name: "{{item.name}}"
                 password: "{{item.password}}"
                 state: present

            loop:
                  - name: user1
                    password: mdp_user1
                  - name: user2
                    password: mdp_user2
                  - name: "{{name3}}"
                    password: "{{stockpswd}}"
register: recap
