---
- hosts: webserver
  remote_user: root
  vars_files:
          - "vars/{{env}}_vars.yml"
          - "vars/{{env}}_secret.yml"
  tasks:
          - name: debug
            debug:
                    msg: "Bonjour ici l'environnement {{env}}"

          - name: "création user"
            when : ansible_distribution == "Ubuntu"
            user:
                 name:"{{item.name}}"
                 password: "{{ttem.name}}"
                 state: present
